### ISSUE TITLE
如何自定义触发 header_widget  click事件

### ISSUE THREAD

**Issue by mogoui** [472647301/tradingview-web-socket#34]
![image](https://user-images.githubusercontent.com/76653351/103495289-40309d00-4e75-11eb-8c1f-57efc6129358.png)

**Comment by 472647301** [comment]
指标可以通过图表方法createStudy创建，样式设置可以通过custom_css_url覆盖，全屏通过浏览器api实现。具体可查阅文档：https://aitrade.ga/books/tradingview/book/Chart-Methods.html

**Comment by mogoui** [comment]
指标和设置 我不需要自定义里面的内容
我只需要跟他一样弹出就行了,有没有方法可以直接弹出来

**Comment by 472647301** [comment]
通过图表方法executeActionById，具体参考：https://aitrade.ga/books/tradingview/book/Chart-Methods.html#executeactionbyidactionid

例如：
```javascript
this._widget.onChartReady(() => {
  // 显示指标对话框
  this._widget?.chart().executeActionById('insertIndicator')
})
```

**Comment by mogoui** [comment]
好了  谢谢您
