### ISSUE TITLE
您好，当选择周线的时候，getBars()方法返回的参数不正确

### ISSUE THREAD

**Issue by wangwei8888** [472647301/tradingview-web-socket#4]
![image](https://user-images.githubusercontent.com/36029972/41773695-8e78a288-764f-11e8-80e9-84a901f0dd4a.png)

当选择周线和月线的时候，getBars()方法resolution参数返回的都是D, 正常应该返回1W和1M。 
这个会导致不断刷新， 请问大神应该如何解决？ @472647301

**Comment by wangwei8888** [comment]
![image](https://user-images.githubusercontent.com/36029972/41775387-4e18f0ec-7656-11e8-892c-d85d493aed6d.png)

虽然可以修改getBars()的代码可以解决周线的问题，但是无法从根本上解决这个bug，因为月线和周线返回的都是D，所以无法区分周线和月线，希望大神 有空修复一下 @472647301 小弟感激不尽

**Comment by 472647301** [comment]
@wangwei8888 tv默认周以及月都是以日线渲染的，你可以在index.js的resolveTVSymbol方法里返回has_weekly_and_monthly:true，这样就会请求周以及月的数据，但是由于我自己部署的后台暂时没有周以及月的数据，所以这一步我没有处理，等后期接入其它平台的数据在处理。

**Comment by wangwei8888** [comment]
谢谢大神，这个问题终于解决了。 😆
