### ISSUE TITLE
大神，请问火币的这个分时图是 如何绘制出来的？

### ISSUE THREAD

**Issue by wangwei8888** [472647301/tradingview-web-socket#5]
![image](https://user-images.githubusercontent.com/36029972/41805470-8b0c08a4-76dd-11e8-8f9c-1a661ca51468.png)

**Comment by 472647301** [comment]
通过widget的createButton方法，参考https://github.com/caozihao/web-react-tradeview/blob/master/src/tradeview/TradeviewPageUtil.js

**Comment by wangwei8888** [comment]
按钮我知道如何创建，但是下面的这个图应该如何绘制呢？
![image](https://user-images.githubusercontent.com/36029972/41806945-5458b7dc-76f9-11e8-940b-132feabba1fe.png)

**Comment by wangwei8888** [comment]
我知道了，图表样式切换到 面积图就好了 😁
![image](https://user-images.githubusercontent.com/36029972/41807036-2399e894-76fb-11e8-8b3f-86d3ac447042.png)
