### ISSUE TITLE
Widget构造器在什么地方初始化的，无法调用方法

### ISSUE THREAD

**Issue by JohnTomcatWu** [472647301/tradingview-web-socket#51]
按照此帮助文档，找不到初始化对象，方法也调不了
https://zlq4863947.gitbook.io/tradingview/4-tu-biao-ding-zhi/widget-constructor
此项目是不是深度阉割了Charting Library ，文件目录也和官版不一致。

**Comment by 472647301** [comment]
没有阉割，只是改了导出方式，具体查看[datafeed.ts](https://github.com/472647301/tradingview-web-socket/blob/master/tradingview-api/src/datafeed.ts)第8行, 导出的widget等同于TradingView.widget

> 按照这个帮助文档，找不到初始化对象，也调不了
> https://zlq4863947.gitbook.io/tradingview/4-tu-biao-ding-zhi/widget-constructor
> 项目是不是绝方法阉割了这个图表库，文件目录也和官方版本。
