### ISSUE TITLE
为什么要send server?

### ISSUE THREAD

**Issue by davidxiaobj** [472647301/tradingview-web-socket#56]
请问一下大神，为什么要send ?不回好像也没问题啊？我应该没理解，
这里有好几处，基本从服务器每得到数据，都send回一下，比如下面，
https://github.com/472647301/tradingview-web-socket/blob/master/react-typescript-demo/src/utils/socket.ts#L135

谢谢

**Comment by 472647301** [comment]
send是传输数据到websocket服务端，api接口返回历史数据之后通过websocket更新实时数据，不send就不会更新实时数据

**Comment by davidxiaowws** [comment]
谢谢
