### ISSUE TITLE
请问页面第一次加载默认添加一些指标怎么处理，谢谢大佬

### ISSUE THREAD

**Issue by lizhengxiang** [472647301/tradingview-web-socket#63]
![image](https://user-images.githubusercontent.com/6184630/148311829-740db1b9-3cad-4806-aec7-eb1ae4016fab.png)

**Comment by 472647301** [comment]
你是想要添加还是移除？添加调createStudy方法，移除调removeAllStudies方法。
具体可参考：https://aitrade.ga/books/tradingview/book/Chart-Methods.html#createstudyname-forceoverlay-lock-inputs-overrides-options
