### ISSUE TITLE
请问大神，如果实现分批加载数据，像火币网那样

### ISSUE THREAD

**Issue by wangwei8888** [472647301/tradingview-web-socket#7]
Datefeeds 初始化的适合设置了1秒 更新一次数据 ，那么 getBars()方法就会每秒调用一次， 那么如果要实现 火币 那种分批加载 历史K 线的话 ，如何控制 请求 频率 （就只在拉动k 线到最左端的时候才去请求）

https://www.huobi.com/zh-cn/coin_coin/exchange/#s=btc_usdt

**Comment by 472647301** [comment]
这个不太清楚
