### ISSUE TITLE
历史数据在哪里绘制的？？

### ISSUE THREAD

**Issue by fangzufa** [472647301/tradingview-web-socket#8]

**Comment by 472647301** [comment]
历史数据通过getBars的onDataCallback方法填充，实时数据通过DataUpdater的onSubscriberDataReceived实现

**Comment by yy0608** [comment]
感谢，请问如果用http来请求历史数据，如何在当前项目修改？

**Comment by 472647301** [comment]
@yy0608 http接口返回数据之后调用onMessage传递history数据就可以了

**Comment by yy0608** [comment]
我也是这么操作的，可是空白哦

**Comment by yy0608** [comment]
@472647301 我是这么做的，但是空白哦，this.onMessage({ data: data.data.sublist })。最后的数据是对象数组

![image](https://user-images.githubusercontent.com/19465036/50587079-6d799780-0eb7-11e9-90d8-0e32cf121f73.png)

**Comment by 472647301** [comment]
确保数据跟ws返回数据结构一致
![image](https://user-images.githubusercontent.com/26315702/50587582-6a7fa680-0eb9-11e9-907c-5b15eedb902e.png)

**Comment by yy0608** [comment]
@472647301 您好，是一样的，确认过了

**Comment by yy0608** [comment]
@472647301 好的，我再确认下

**Comment by 472647301** [comment]
你追踪一下数据吧，看看是哪里出了错.

**Comment by yy0608** [comment]
@472647301 有些字段不清楚是什么，像base_vol、quote_vol和count等，文档也没找到，下面截图里分别是您的数据和我们的数据。

![image](https://user-images.githubusercontent.com/19465036/50588245-24781200-0ebc-11e9-92e0-15dfe5816100.png)

**Comment by 472647301** [comment]
base_vol这些字段是fcoin定义的，对应list.push对象里的字段，如果你无法更改你的数据源可以更改list.push

**Comment by yy0608** [comment]
@472647301 感谢，可以更改数据源，只是不知道这些字段的意思？请问有地方可以查到吗

**Comment by yy0608** [comment]
@472647301 加了这些字段，还是没有显示k线图，有没有可能不是这个原因

**Comment by yy0608** [comment]
@472647301 您可以用静态数据测试一下，直接用onMessage传history好像是不行的

> onMessage传递history数据就可以了

**Comment by 472647301** [comment]
我明天试试吧，可能是执行顺序的问题。你的history http请求应该在getBars里面执行。目前是在created，这时候图表并没用初始化完成

**Comment by 472647301** [comment]
查看[这里](https://b.aitrade.ga/books/tradingview/book/UDF.html#k%E7%BA%BF%E6%9F%B1)，以及[对比这里](https://github.com/472647301/tradingView-webSocket/blob/master/static/tradeview/datafeeds/udf/lib/history-provider.js)

**Comment by yy0608** [comment]
好的，辛苦大神了

**Comment by yy0608** [comment]
@472647301 大神有抽空试试吗

**Comment by 472647301** [comment]
你把请求写到subscribe里就好了，需要from跟to的话可以从getBars传进去，类型这样
![image](https://user-images.githubusercontent.com/26315702/50632040-8cdcf700-0f81-11e9-93b5-76e1932320a3.png)

**Comment by yy0608** [comment]
@472647301 谢谢，我试试

**Comment by yy0608** [comment]
@472647301 图形可以了，非常感谢！

**Comment by yy0608** [comment]
@472647301 抱歉，按您的方法，图形是空白的。图形依然会使用websocket的数据填充

**Comment by 472647301** [comment]
在onMessage里你要区分历史数据和实时数据，先渲染历史数据在渲染实时数据

**Comment by yy0608** [comment]
大神我的图标显示没有右侧的数据显示，也没有底部的成交量

**Comment by yy0608** [comment]
![image](https://user-images.githubusercontent.com/19465036/50944074-f0a77880-14c9-11e9-81d0-3224cc57c4e7.png)

**Comment by yy0608** [comment]
叨饶了，是我的数据太小了，都是0.005以下的
