### ISSUE TITLE
react demo not work

### ISSUE THREAD

**Issue by davidxiaobj** [472647301/tradingview-web-socket#83]
运行 react ts demo失败了，怎么回事？

![Screen Shot 2022-04-10 at 12 49 20 pm](https://user-images.githubusercontent.com/4176280/162599106-7ffaca8b-e79b-4250-8e74-34fa7129de68.png)

好像./public/charting_library/charting_library.js没加载成功，文件存在

**Comment by orange-chn** [comment]
我也遇到了这个问题，请问有解决吗

**Comment by 472647301** [comment]
需要v20或以上版本tradingview

**Comment by davidxiaobj** [comment]
我试了../charting_library 及tradingview的最新charting_library,一样的错误， 
为啥vue的work？
thanks
