### ISSUE TITLE
Update Request on the Tradingview Charting Libary

### ISSUE THREAD

**Issue by Adlerkampf** [472647301/tradingview-web-socket#88]
Hey, could you please update the Tradingview Charting Libary? Because the current version of it present in the project seem pretty old.

嘿，你能不能更新一下Tradingview图表库的内容？因为项目中目前的版本似乎很旧。

**Comment by 472647301** [comment]
Sorry, I don't have more time to deal with it at the moment, I plan to update when I'm done with work, but may not provide charting_library resources

**Comment by 472647301** [comment]
已更新到v20.033
