### ISSUE TITLE
老大错误

### ISSUE THREAD

**Issue by raymond-etet** [472647301/tradingview-web-socket#99]
1. **yarn install**

yarn install v0.25.2
(node:12116) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
warning fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@vue/cli-service@4.5.11" has unmet peer dependency "vue-template-compiler@^2.0.0".
warning "sass-loader@8.0.2" has unmet peer dependency "sass@^1.3.0".
warning "sass-loader@8.0.2" has unmet peer dependency "fibers@>= 3.1.0".
[4/4] Building fresh packages...
[-/4] ⡀ waiting...
[-/4] ⡀ waiting...
[-/4] ⡀ waiting...

2. **yarn serve**

yarn serve v0.25.2
(node:6888) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
$ vue-cli-service serve
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                      上午10:42:40

 error  in ./src/App.vue?vue&type=style&index=0&id=7ba5bd90&lang=scss&scoped=true

Syntax Error: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1

**Comment by 472647301** [comment]
fibers需要node特定版本
